version: 0.0
os: linux
files:
  - source: app.py
    destination: /home/ubuntu
  - source: requirements.py
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu/app.py
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: /bin/bash
      timeout: 300
      runas: ubuntu
      arguments:
        - -c
        - |
          cd /home/ubuntu
          python3 -m venv myenv
          source myenv/bin/activate
  ApplicationStart:
    - location: /bin/bash
      timeout: 300
      runas: ubuntu
      arguments:
        - -c
        - |
          cd /home/ubuntu
          source myenv/bin/activate
          pip install flask
          sudo pkill -f app.py || true
          python app.py &
