version: 0.0
os: linux
files:
  - source: /*
    destination: /home/ubuntu
permissions:
   - object: /home/ubuntu/app.py
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 755
  - object: /home/ubuntu/scripts/install_dependencies.sh
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 755
  - object: /home/ubuntu/scripts/start_app.sh
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: /home/ubuntu/scripts/install_dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/scripts/start_app.sh
      runas: ubuntu
