version: 0.0
os: linux
files:
  - source: /app.py
    destination: /home/ubuntu
  - source: /requirements.txt
    destination: /home/ubuntu/requirements.txt
  - source: /scripts/install_dependencies.sh
    destination: /home/ubuntu/scripts/install_dependencies.sh
  - source: /scripts/start_app.sh
    destination: /home/ubuntu/scripts/start_app.sh
permissions:
  - object: /home/ubuntu/app.py
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: /bin/bash -c "sudo pkill -f app.py || true" # Add the pkill command before app start
      runas: ubuntu
    - location: scripts/start_app.sh
      runas: ubuntu
